### ISSUE TITLE
Duplicate CORS Header

### ISSUE THREAD

**Issue by BoredLama** [rleroi/stremio-anime#2]
Hi! I'm glad I managed to find this repo on Github.

I found this add-on in Stremio's catalog and noticed it didn't work on the desktop version or the web version of Stremio. It does seem to work on Android though.

The reason it doesn't work on the web and desktop versions seems to be because CORS is set twice in the reply headers from this add-on:

<img width="878" alt="screen shot 2018-12-19 at 18 13 54" src="https://user-images.githubusercontent.com/43473329/50232607-514f0400-03a9-11e9-95f0-49ec3179ce83.png">

<img width="528" alt="screen shot 2018-12-19 at 18 14 10" src="https://user-images.githubusercontent.com/43473329/50232612-54e28b00-03a9-11e9-9f65-ab63bebc6831.png">

As you can see, `Access-Control-Allow-Origin` is set to `*, *` instead of `*`. This can happen when a header is set with the same value 2 times, and the headers are then concatenated into one value.

Checked in all browsers, they all fail with the same error. You can check ur add-on on the web version by going to: http://app.strem.io/shell-v4.4/#/

When I tested on the Android version, it worked, but there are still streams that seem to fail, for example I searched for "Mushishi" and selected "Mushishi (Dub)" and all streams fail for it, for other shows only some streams fail but not all.

I really hope you finish this add-on, it's awesome!

**Comment by BoredLama** [comment]
I've also just tested this add-on locally, the catalogs seem to work fine locally. There is no duplicate CORS set. Is it possible that the server you are hosting this add-on on injects CORS on the fly in the response headers?

**Comment by rleroi** [comment]
I've noticed the double cors header yesterday, i didnt know that the stremio addon sdk already sets them. It's fixed now!
