### ISSUE TITLE
Stremio add-on donations

### ISSUE THREAD

**Issue by BoredLama** [rleroi/stremio-anime#8]
I saw you initially posted a donation link in the add-on description.

Although this is not part of the sdk yet, I did see this ticket for a donation implementation created by one of the developers:
https://github.com/Stremio/stremio-addon-sdk/issues/34

They seem to be planning donation options that are well positioned in the stremio user interface for add-on developers.

Maybe it would be useful to keep an eye on the progress of that ticket.

**Comment by rleroi** [comment]
Thanks, I'll follow the topic
